using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using IronRuby.Compiler.Ast;

namespace Fructose.Compiler
{
    public class Compiler
    {
        public const string IndentSpacing = "    ";
        static Dictionary<NodeTypes, AstNodeGenerator> generators;
        static Compiler()
        {
            generators = (from type in System.Reflection.Assembly.GetExecutingAssembly().GetTypes()
                          where type.IsSubclassOf(typeof(AstNodeGenerator))
                          select new
                          {
                              v = (AstNodeGenerator)Activator.CreateInstance(type),
                              k = type.GetCustomAttributes(false).OfType<GeneratorAttribute>().Single().NodeType
                          })
                         .ToDictionary(pair => pair.k, pair => pair.v);
        }

        int indentLevel = 0;
        StringBuilder sb = new StringBuilder();
        public SourceUnitTree tree { get; private set; }
        public Transformer.Transformations Transformations { get; private set; }
        public string[] signature;
        public Compiler(SourceUnitTree tree, string source = null)
        {
            if (source == null)
                signature = new string[0];
            else
            {
                signature = new string[] {
                    "// " + source.MD5(),
                    "// Generated by Fructose on " + DateTime.Now.ToShortDateString() + " by " + Environment.UserName,
                    "//"
                };
            }
            this.tree = tree;
        }

        internal void AppendLine(string fmt, params string[] args)
        {
            for (int i = 0; i < indentLevel; i++)
                sb.Append(IndentSpacing);

            if (args.Length > 0)
                sb.AppendFormat(fmt + "\n", args);
            else
                sb.AppendLine(fmt);
        }

        internal void Indent()
        {
            indentLevel++;
        }
        internal void Dedent()
        {
            indentLevel--;
        }

        public string Compile(Transformer.Transformations transformations)
        {
            Transformations = transformations;

            sb.AppendLine("<?php");
            foreach(var c in signature)
                sb.AppendLine(c);
            sb.AppendLine(@"error_reporting(E_ALL | ~E_STRICT);
require_once 'libfructose.php';
if(!isset($_stack))
	global $_stack;
global $_lambda_objs;
if(!isset($_locals))
	global $_locals;
global $_gthis;
global $_globals;
");

            foreach (var stmt in tree.Statements)
                CompileNode(stmt);

            return sb.ToString();
        }

        public void CompileNode(Node node)
        {
            CompileNode(node, NodeParent.Terminator);
        }
        public void CompileNode(Node node, NodeParent parents)
        {
            if (node == null)
                return;

            if (!generators.ContainsKey(node.NodeType))
                throw new NotImplementedException("NodeType " + node.NodeType + " not supported yet: " + node.Location.ToString());

            generators[node.NodeType].Compile(this, node, parents);
        }
    }
}
